### ISSUE TITLE
Add YEAR and QUARTER folders for downloaded riles in <filings> folder exactly as in <idxfiles> folder 

### ISSUE THREAD

**Issue by kuatroka** [dlouton/sectoolkit#1]
First of all, thanks for this tool. It's small and neat.

The ask is as in the title. Currently, the `idxfiles` folder does have subfolders split by YEAR and QUARTER and the `filings ` folder itself doesn't. Is there a way to add a flag or a parameter to enable the creation of folders with the YEAR and QUARTER identifiers?

Thanks

![image](https://user-images.githubusercontent.com/9093546/159771239-cf59ac22-ac4e-412b-84ee-f752e2fd0a68.png)

**Comment by dlouton** [comment]
Hi -

I will look into this.  Initially it made sense to just save the filings in a tree structure based on the CIKs of the filing firm.  The filingArchive object has an attribute that stores the local path of the filing, so it is very feasible to filter a data frame containing SEC index records, using whatever criteria make sense for your project, and then access the filing content using the filingDocument objects that filingArchive creates.  With that in mind, I am not sure why an alternative structure for the file storage tree would be needed, given that the local path for each filing is easily accessible.  However, if you could be more specific about your use case, that would be helpful.

Thanks again for your feedback.

Dave Louton

—————-
David Louton, Ph.D.
Professor of Finance
Bryant University



________________________________
From: kuatroka ***@***.***>
Sent: Wednesday, March 23, 2022 2:36:35 PM
To: dlouton/sectoolkit ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dlouton/sectoolkit] Add YEAR and QUARTER folders for downloaded riles in <filings> folder exactly as in <idxfiles> folder (Issue #1)


First of all, thanks for this tool. It's small and neat.

The ask is as in the title. Currently, the idxfiles folder does have subfolders split by YEAR and QUARTER and the filings folder itself doesn't. Is there a way to add a flag or a parameter to enable the creation of folders with the YEAR and QUARTER identifiers?

Thanks

[image]<https://user-images.githubusercontent.com/9093546/159771239-cf59ac22-ac4e-412b-84ee-f752e2fd0a68.png>

**Comment by kuatroka** [comment]
Here goes the logic, David. Though admittedly, it’s the logic of what I see as needed. I’ll share the objective and the steps of what I’m trying to do and you will decide. To note, I’m not a proper dev, so I’m just trying to make things work, which for sure will not be an ideal way how an engineer would do. For now, I’m only dealing with 13F filings.

1. I want to create two processes, A that downloads full load of 13F filings from 1993 till today and B that on a daily basis download only the delta ( new, daily additions)

2. A would download all the data in a local directory with subfolders identified with its YEAR and QUARTER.

3. Another process - B-Parse would parse every filing .txt file for every  year and quarter one by one and write the processes data to a DB table. Once all the checks are done (that the DB table has the same amount of entries for each quarter as the files in the local QUARTER folder) the folder for that YEAR/QUARTER combination is deleted and the local hard drive space is released. 
This process would go through all the YEARS and QUARTERS and at the end, the DB table would be filled with structured 13F data and all the local files would be deleted ro reclaim disk space.
There is a caveat to this process. Before parsing and writing the filing’s content to the DB table, a piece of code would check each filing if it has an <XML> tag. If yes, it gets parsed and if not, the file gets written to a different folder with YEAR/QUARTER identifier and does not get deleted at the end of the process. It needs to be kept for further parsing efforts as it’s not as trivial as the XML based files.

4. The process B would create two folders, one for the current month data to be daily filled and one the previous month. Once the current month ends and becomes the previous month, the. The data from the previous month folder is deleted and the hard disk space is reclaimed.

Hopefully, this explains the ask. I think the data with clearly identified YEAR and MONTH, would be easier to check against the DB table and later delete only processed quarters.

A separate question, is there a way to see the list of filings or URLs that will be downloaded after the time and Filing Type filter is applied, but before the data download is actually triggered?

Thanks

**Comment by dlouton** [comment]
Sorry to be slow to get back to you on this.  I have implemented a few new features which may be of help to you.  

First, in the filingArchive class, I have added two new methods: copy_filingArchive(), which takes the destination file path as argument, and delete_filingArchive(), which deletes the filing archive from the default filing cache.  These would allow you to download the files to the default filing cache, move them to the directory structure of your choice and then delete the original files in order to save space.  I admit that this is not precisely what you requested, but the problem with putting everything from a particular quarter into one directory is that the filename is not guaranteed to be unique unless you combine the last two levels of the SEC filepath.  For example edgar/data/1000097/0001000097-21-000008.txt would need to become something like year/quarter/1000097_0001000097-21-000008.txt.  Because of the filename problem, quite a bit of the filename logic currently included in the package would have to be revised in order to provide full support for the alternate directory structure that you have requested.  However, in the meantime, you could use the following code to implement a temporary solution along the lines that I have suggested:

```
# pip install --upgrade sectoolkit

import sectoolkit as sec
import pathlib

filings_qtr = './filings_qtr'
start_yr = 2019
end_yr = 2022

# Set user agent
user_agent_str = "My Corp, test@mycorp.com"

# Set filter to select only 13F filings.
filters = {'Form Type': ['13F-NT/A', '13F-HR', '13F-HR/A', '13F-NT']}

for year in range(start_yr, end_yr):
    for qtr in range(1,5):
        print(year, qtr)
        
        # Retrieve the index records for a specific quarter
        idx = sec.idx(start_year = year, end_year = year, start_quarter = qtr, end_quarter = qtr, \
              datadir = '.\secdata', user_agent = user_agent_str)
        
        # Filter index records
        idx.filter_index(filters)
        
        ## For testing purposes only, restrict the index to the first 5 13F filings of the quarter
        idx.working_idx = idx.working_idx.head()
        
        # Download the filings into the default directory structure
        idx.fetch_filings(headers = True)
        
        # Copy the filings to the year/quarter directory structure
        for fname in idx.working_idx.Filename:
            new_fname = '_'.join(fname.split('/')[-2:])
            new_localpath = '/'.join([filings_qtr, str(year), 'QTR'+str(qtr), new_fname])
            # Make sure that the directory path exists
            path = pathlib.Path(new_localpath)
            path.parent.mkdir(parents=True, exist_ok=True)
            f = sec.filingArchive(fname)
            f.copy_filingArchive(new_localpath)
#             print(new_localpath)
            
        # Clear the default directory structure to save disk space
        idx.clear_filing_cache()
        idx.clear_header_cache()       
```

On the other hand, you may be better off staying with the existing directory structure since these files are actually archives that contain all of the documents connected with a particular filing.  Note that the filingArchive.localfilename property will tell you exactly where the archive file is located in case you want to access it directly.  However, you might prefer to use the get_filingArchive() method to extract the files contained within the archive.  So instead of following the f = sec.filingArchive(fname) statement shown above with the copy_filingArchive() method, you could do something like the following:

```
f.get_filingArchive()
text = f.files[0].body
```
Then parse the text extracted from within the filing body and do whatever analysis you want to do.  If the filing does not parse correctly, you could then use f.copy_filingArchive(new_localpath) to save the entire archive file for further analysis, or just write the text of the actual filing to the filepath of your choice.

In answer to your last question, note that the idx.filter_index() step saves the resulting records in Pandas dataframe form as the working_idx attribute of the index object, i.e. idx.working_idx in the example code shown above.  Note that in the example I only took the first five 13F filings for each quarter, so you would need to delete or comment out the idx.working_idx = idx.working_idx.head() line.

I hope this is helpful. I will continue to consider whether there is a clean way to offer different directory structure options without unduly complicating the the interaction of the other classes in the package with the index class.

**Comment by kuatroka** [comment]
Thanks for this @dlouton. I must confess I thought you weren't working on it and I didn't update you that, at least, for now I changed my immediate priorities and the folder structure is not on my top 5 list of things to do. In any case, if you want to see how it was implemented elsewhere, the [sec-edgar](https://sec-edgar.github.io/sec-edgar/usage.html#saving-filings) project does. I believe the downloads are stored in the format
  -- /YEAR
       ---/QUARTER
             ----/CIK1
                  ----FILE1
                  ----FILE2
             ----/CIK2
            ----/CIK N....

Anyway, I realised I might need to keep the raw files a while longer, so no need to delete them immediately. Also I realised your code does check for duplicates so there is no danger of downloading the same file twice. 

I have been working on a code that takes all the downloaded files one by one, checks if it's XML or NOT and if yes, parses it and writes it to a local SQLite db. If not, it skips it and goes to the next file. It took me 3 days to parse and write it to the db. Now I'll look into improving the code as it's very inefficient. It works, but it's slow. Once that is done, I'll use that code to create another piece of code that deals only with delta files (which would be based on your code but would only download the current quarter or two). I also want to try and move from the SQLite db to the Duckdb.
 
I have also created another code that only identifies if the file is XML or NOT, creates a flag and writes all the data for all files into another table so I can later start working on parsing the non-XML files too.

Your code helped me, so as a matter of courtesy, if you which, I'd be happy to share with you the 13F filing parsing code for the XML based files that I wrote/copied/cannibalised from other places that.
It's a very infantile code, but it works. Let me know if you want it.

Cheers.

**Comment by dlouton** [comment]
Thanks for the offer to share your 13F parsing code.  That would be very helpful.

**Comment by kuatroka** [comment]
1. Run first huge cell in this jupyter notebook
2. In the 2nd one change the file for your local SQLite db file and run the cell
3. In the 3rd cell, pass the directory with your downloaded filings as the only parameter to the function

If all goes well, it should trigger the parsing and data writing process
[parse_13f_from_file_alpha1.zip](https://github.com/dlouton/sectoolkit/files/8565300/parse_13f_from_file_alpha1.zip)

**Comment by dlouton** [comment]
Thanks.

**Comment by kuatroka** [comment]
A bit of a separate question...


Do you know of a possible logic/conceptual process or an actual module that would take a CIK and much more importantly CUSIP and convert it to a corresponding TICKER? At least for US market? Thanks

**Comment by kuatroka** [comment]
Closing it as not needed anymore

**Comment by kuatroka** [comment]
A better, cleaner and less buggy version of the parsing code. It only parses the XML based filings. Unfortunately, I'm struggling with approaching the parsing the old, ASCII text based one.



```
from datetime import datetime
from bs4 import BeautifulSoup as bs
import re
import pandas as pd


def end_to_end_parsing(file_path):

    def work_content_extract(file_path):
        """extracting 1. xml or not flag, 2. xml part of filings, SEC header part """
        open_file = open(file_path,"r")
        file_content = open_file.read()
        open_file.close()

        #find block of text between two words/tags/strings
        start_header  = "<SEC-HEADER>"
        end_header = "</SEC-HEADER>"
        block_header_search = re.compile(f'{start_header}.*?{end_header}',re.DOTALL)
        pages_header = re.findall(block_header_search, file_content)

        # check if file is XML or not
        xml_tag_search = re.compile(r"<xml>", flags=re.IGNORECASE)
        if xml_tag_search.search(file_content):
            xml_flag = "YES"

            # xml block search
            start_xml  = "<XML\>"
            end_xml = "<\/XML\>"
            block_xml_search = re.compile(f'{start_xml}(.*?){end_xml}',re.DOTALL)
            pages_xml = re.findall(block_xml_search, file_content)

            if len(pages_xml) == 0:
                reportType = ""
                document0 = ""
                document1 = ""
            elif len(pages_xml) == 1:
                document0 = bs(pages_xml[0], "xml")
                coverPage = document0.find("coverPage")
                reportType = coverPage.find("reportType").text.strip()
                document1 = ""
            if len(pages_xml) > 1:
                document0 = bs(pages_xml[0], "xml")
                coverPage = document0.find("coverPage")
                reportType = coverPage.find("reportType").text.strip()
                document1 = bs(pages_xml[1], "xml")

        else:
            xml_flag = "NO"
            pages_xml = []
            reportType = ""
            document1 = ""

        return pages_header, pages_xml, xml_flag, reportType, document1


    def parse_institutionalInvestorInfo(file_path):
        dataDictionary = dict()
        dataDictionary["edgar_path"] = file_path
        periodOfReport = datetime.strptime(re.compile(r"(?<=CONFORMED PERIOD OF REPORT:).*")\
                                           .search(pages_header[0]).group(0).strip(),"%Y%m%d").date()
        report_Year, report_Quarter = periodOfReport.year, (periodOfReport.month-1)//3 + 1 

        dataDictionary["accessionNumber"] = re.compile(r"(?<=ACCESSION NUMBER:).*").search(pages_header[0]).group(0).strip()
        dataDictionary["cikManager"] = re.compile(r"(?<=CENTRAL INDEX KEY:).*").search(pages_header[0]).group(0).strip()
        dataDictionary["managerName"] = re.compile(r"(?<=COMPANY CONFORMED NAME:).*").search(pages_header[0]).group(0).strip()
        dataDictionary["periodOfReport"] = periodOfReport
        dataDictionary["report_Quarter"] = report_Quarter
        dataDictionary["report_Year"] = report_Year
        dataDictionary["submissionType"] = re.compile(r"(?<=CONFORMED SUBMISSION TYPE:).*").search(pages_header[0]).group(0).strip()
        dataDictionary["filedAsOfDate"] = datetime.strptime(re.compile(r"(?<=FILED AS OF DATE:).*")\
                                                          .search(pages_header[0]).group(0).strip(), "%Y%m%d").date()
        dataDictionary["xml_flag"] = xml_flag
        dataDictionary["created_at"] = datetime.now()

        # dataDictionary = dict()
        dataDictionary["edgar_path"] = file_path
        if xml_flag == "NO":

            dataDictionary["isAmendment"] = ""
            dataDictionary["amendmentType"] = ""
            dataDictionary["entryTotal"] = int('0'+ '')
            dataDictionary["valueTotal"] = float('0.0'+ '')
            dt = pd.DataFrame.from_dict([dataDictionary]) 

        else:
            if len(pages_xml) == 0:
                dataDictionary["isAmendment"] = ""
                dataDictionary["amendmentType"] = ""
                dataDictionary["entryTotal"] = int('0'+ '')
                dataDictionary["valueTotal"] = float('0.0'+ '')
                dt = pd.DataFrame.from_dict([dataDictionary]) 

            else:
                document = bs(pages_xml[0], "xml")
                # get sections
                coverPage = document.find("coverPage")
                summaryPage = document.find("summaryPage")
                # get data
                if coverPage.find("isAmendment") is not None:

                    if coverPage.find("isAmendment").text.strip() == "true":
                        dataDictionary["isAmendment"] = coverPage.find("isAmendment").text.strip()
                        if coverPage.find("amendmentType"):
                            dataDictionary["amendmentType"] = coverPage.find("amendmentType").text.strip()
                        else:
                            dataDictionary["amendmentType"] = ""
                    else:
                        dataDictionary["isAmendment"] = coverPage.find("isAmendment").text.strip()
                        dataDictionary["amendmentType"] = ""
                else:
                    dataDictionary["isAmendment"] = ""
                    dataDictionary["amendmentType"] = ""

                if summaryPage is not None:
                    if summaryPage.find("tableEntryTotal").text.strip():
                        dataDictionary["entryTotal"] = int(float(summaryPage.find("tableEntryTotal").text.strip()))
                    else:
                        dataDictionary["entryTotal"] = int('0'+ '')
                    dataDictionary["valueTotal"] = float(summaryPage.find("tableValueTotal").text.strip() + "000")
                else:
                    dataDictionary["entryTotal"], dataDictionary["valueTotal"] = int('0'+ ''),  float('0.0'+ '')

                # create dataframe   
                dt = pd.DataFrame.from_dict([dataDictionary])

        return(dt)



    def parse_institutionalInvestorPortfolio(file_path):
        check = re.compile("13F HOLDINGS REPORT|13F COMBINATION REPORT")
        if check.search(reportType) is not None and len(pages_xml) > 1:

            portfolio = list()
            # find all securities held

            securities = document1.find_all('infoTable')
            for row in securities:
                portfolioDict = dict()
                portfolioDict["edgar_path"] = file_path
                portfolioDict["cusip"] = row.find("cusip").text.strip()  
                portfolioDict["nameOfIssuer"] = row.find("nameOfIssuer").text.strip()
                portfolioDict["titleOfClass"] = row.find("titleOfClass").text.strip() 
                portfolioDict["sharesValue"] = float(row.find("value").text.strip()  + "000")
                portfolioDict["sharesHeldAtEndOfQtr"] = int(float(row.find("sshPrnamt").text.strip())) 

                try:
                    portfolioDict["sharePriceAtEndOfQtr"] = round(portfolioDict["sharesValue"] / portfolioDict["sharesHeldAtEndOfQtr"], 2)
                except ZeroDivisionError:
                    portfolioDict["sharePriceAtEndOfQtr"] = float(int('0'+''))

                portfolioDict["securityType"] = row.find("sshPrnamtType").text.strip() 

                if row.find("putCall") is not None:
                    portfolioDict["putCall"] = row.find("putCall").text.strip()
                else:
                    portfolioDict["putCall"] = ""

                portfolio.append(pd.DataFrame.from_dict([portfolioDict]))

            # concatanate secutires
            dtPortfolio = pd.concat(portfolio, sort = False, ignore_index = True)
        else:
            dtPortfolio = pd.DataFrame.from_dict([{"cusip": "", "nameOfIssuer": "", "titleOfClass": "", "sharesValue": float('0.0'+''), "sharesHeldAtEndOfQtr": int('0'+''), "sharePriceAtEndOfQtr": float('0.0'+''), "securityType": "", "putCall": "", "edgar_path": file_path}])

        return(dtPortfolio)
    
    pages_header, pages_xml, xml_flag, reportType, document1 = work_content_extract(file_path)
    df1, df2 = parse_institutionalInvestorInfo(file_path), \
               parse_institutionalInvestorPortfolio(file_path)

    data = pd.merge(df1, df2, on="edgar_path")

    data.insert(0, "ID", data.accessionNumber.map(str) + '-' + data.cikManager.map(str) + '-' + data.index.map(str))

    column_names = ["ID", "accessionNumber", "cikManager", "managerName","periodOfReport", "report_Quarter", "report_Year", "submissionType", "filedAsOfDate", "isAmendment", "amendmentType", "entryTotal", "valueTotal", "cusip", "nameOfIssuer", "titleOfClass", "sharesValue", "sharesHeldAtEndOfQtr", "sharePriceAtEndOfQtr", "securityType", "putCall", "xml_flag", "created_at", "edgar_path" ]
    data.astype({"ID": str, 
                     "accessionNumber": str,
                     "cikManager": int,
                     # "periodOfReport": 'datetime64[ns]',
                     "report_Quarter": int,
                     "report_Year": int,
                     "submissionType": str,
                     "isAmendment": bool,
                     "amendmentType": str,
                     # "filedAsOfDate": 'datetime64[ns]',
                     "entryTotal": int,
                     "valueTotal": float,
                     "cusip": str,
                     "nameOfIssuer": str,
                     "titleOfClass": str,
                     "sharesValue": float,
                     "sharesHeldAtEndOfQtr": int,
                     "sharePriceAtEndOfQtr": float,
                     "securityType": str,
                     "putCall": str,
                     "xml_flag": str,
                     "created_at": 'datetime64[ns]',
                     "edgar_path": str
                    })

    data = data.reindex(columns=column_names)
    
    return data

```

Run the function by passing it the directory where the filings .txt files are. Make sure there is no "/" at the end of the link
`data = end_to_end_parsing(dir_path)`

data is the pandas df with parsed file.

This code doesn't include the writing to the db. Cheers
